/* Generated By:JavaCC: Do not edit this line. JSONPathCompilerTreeConstants.java Version 5.0 */
public interface JSONPathCompilerTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTARRAY = 1;
  public int JJTOBJECT = 2;


  public String[] jjtNodeName = {
    "EXPRESSION",
    "ARRAY",
    "OBJECT",
  };
}
/* JavaCC - OriginalChecksum=233298ef07e949fb12559ddd204d6205 (do not edit this line) */
